<a href="https://colab.research.google.com/github/Rohsha/CE888/blob/master/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import itertools

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import accuracy_score as acc
from sklearn.metrics import make_scorer, confusion_matrix
from sklearn.dummy import DummyRegressor, DummyClassifier
from sklearn.preprocessing import LabelEncoder

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv', header=None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
## Copy values and keep
test_data = df.copy()
df = df.loc[:, 1:]  ##first column is just number of jokes, and not ratings
arr = df.values
print(arr.shape)

(24983, 100)


In [0]:
## Take all rated jokes. If not rated don't add.
## np.where returns an ndarray with all elements which satisfy the condition (x), and then all elements which don't satisfy the condition
## Over here first array is all rows, and 2nd array is all columns indices where it is not 99
## Use this to understand, why it is used inside the Replace Function
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)
new_arr, idx 

(array([[99.  ,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
        [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
        [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
        ...,
        [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
        [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
        [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]]),
 (array([14015, 22612, 16609, ..., 13667, 20911, 15500]),
  array([74, 64,  2, ..., 10,  6, 19])))

In [0]:
print(idx)
print(idx[0][1], idx[1][1])

(array([14015, 22612, 16609, ..., 13667, 20911, 15500]), array([74, 64,  2, ..., 10,  6, 19]))
22612 64


In [0]:
n_latent_factors = 50

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001, weight_decay=0.1):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * (latent_item_features[item_id])
    latent_item_features[item_id] -= alpha * err * (user_pref_values)
    return err
    

def sgd(iterations=100):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                # if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        # if (iteration % 100) == 0:
        #     print('MSE ', iteration, ': ', mse)
        print('MSE ', iteration, ': ', mse)


In [0]:
sgd()

MSE  0 :  28.499602560718575
MSE  1 :  25.03291368086652
MSE  2 :  24.94713944856626
MSE  3 :  24.87804649505107
MSE  4 :  24.817132151328895
MSE  5 :  24.757047271881433
MSE  6 :  24.690283471420283
MSE  7 :  24.60795927523813
MSE  8 :  24.498582194447685
MSE  9 :  24.346847029676212
MSE  10 :  24.132864745234592
MSE  11 :  23.832798269196395
MSE  12 :  23.422606601424253
MSE  13 :  22.886698169555878
MSE  14 :  22.23098502749563
MSE  15 :  21.493875878368044
MSE  16 :  20.743394927992995
MSE  17 :  20.054608660333262
MSE  18 :  19.480119862027028
MSE  19 :  19.035709666545117
MSE  20 :  18.707883855331676
MSE  21 :  18.470733484778858
MSE  22 :  18.298623738246388
MSE  23 :  18.17131898438214
MSE  24 :  18.074369287152212
MSE  25 :  17.997853710303026
MSE  26 :  17.93501021899553
MSE  27 :  17.88118892606616
MSE  28 :  17.83313828463562
MSE  29 :  17.788536214235716
MSE  30 :  17.74568450830639
MSE  31 :  17.703309230714478
MSE  32 :  17.660429957903844
MSE  33 :  17.61627422129409
M

In [0]:
def validation_check():
  error = []
  prediction = latent_user_preferences.dot(latent_item_features.T)
  for i in range(len(idx[0])):
    predicted_rating = prediction[idx[0][i]][idx[1][i]]
    actual_rating = arr[idx[0][i]][idx[1][i]]
    err = predicted_rating - actual_rating
    error.append(err)
  mse = (np.array(error) ** 2).mean()
  print('Validation MSE: ', mse)


In [0]:

validation_check()

Validation MSE:  17.40694818348049


In [0]:
### Creating new validation arrays from original data randomly again
for i in range(10):
  new_arr, idx = replace(arr, 0.1)
  validation_check()

Validation MSE:  13.164094672889279
Validation MSE:  13.178026007754523
Validation MSE:  13.143826322899601
Validation MSE:  13.200318830280587
Validation MSE:  13.133465276417263
Validation MSE:  13.131730838361424
Validation MSE:  13.177710839217866
Validation MSE:  13.186039507489362
Validation MSE:  13.156025456110102
Validation MSE:  13.221825704730675


In [0]:
prediction = latent_user_preferences.dot(latent_item_features.T)

In [0]:
### Prediction values on entire Test Dataset

values = [zip(df.values[i], prediction[i]) for i in range(prediction.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns
comparison_data

1    ...                          100
0      (-7.82, -0.28740648663788665)  ...  (99.0, -3.1116849577270895)
1          (4.08, 6.948943070275182)  ...    (1.07, 6.398088303987081)
2          (99.0, 6.043059257814349)  ...    (99.0, 5.002824544230709)
3          (99.0, 3.945428301073081)  ...    (99.0, 3.878517642946397)
4           (8.5, 2.731726166737577)  ...     (1.6, 2.387118057227503)
...                              ...  ...                          ...
24978      (0.44, 3.390067977851301)  ...     (7.43, 6.52269448658623)
24979      (9.13, 2.502238151225292)  ...    (8.45, 6.692573467745356)
24980   (99.0, -0.10276111774176172)  ...   (99.0, 0.8960041505990806)
24981     (99.0, 3.3999803633925487)  ...   (99.0, 0.3488111464974849)
24982     (2.43, 1.6843240986210966)  ...   (99.0, 3.8765088222098534)

[24983 rows x 100 columns]

In [0]:
jokes_ratings = pd.DataFrame(prediction)
mean_idx = jokes_ratings.mean()
min_idx = mean_idx.idxmin()
max_idx = mean_idx.idxmax()
print('Worst Joke ID predicted: ', min_idx, '; Average Rating: ', mean_idx[min_idx])
print('Best Joke ID predicted: ', max_idx, '; Average Rating: ', mean_idx[max_idx])

Worst Joke ID predicted:  57 ; Average Rating:  -3.9873021561228197
Best Joke ID predicted:  49 ; Average Rating:  3.5181498782131433
